import numpy as np
import tensorflow as tf
from tensorflow.python.ops import tensor_array_ops, control_flow_ops


class Reward(object):
    def __init__(self, lstm, update_rate):
        self.lstm = lstm
        self.update_rate = update_rate

        self.num_vocabulary = self.lstm.num_vocabulary
        self.batch_size = self.lstm.batch_size
        self.emb_dim = self.lstm.emb_dim
        self.hidden_dim = self.lstm.hidden_dim
        self.sequence_length = self.lstm.sequence_length
        self.start_token = tf.compat.v1.identity(self.lstm.start_token)
        self.learning_rate = self.lstm.learning_rate

        self.g_embeddings = tf.compat.v1.identity(self.lstm.g_embeddings)
        self.g_recurrent_unit = self.create_recurrent_unit()  # maps h_tm1 to h_t for generator
        self.g_output_unit = self.create_output_unit()  # maps h_t to o_t (output token logits)

        #####################################################################################################
        # placeholder definition
        self.x = tf.compat.v1.placeholder(tf.compat.v1.int32, shape=[self.batch_size,
                                                 self.sequence_length])  # sequence of tokens generated by generator
        self.given_num = tf.compat.v1.placeholder(tf.compat.v1.int32)

        # processed for batch
        with tf.compat.v1.device("/cpu:0"):
            self.processed_x = tf.compat.v1.transpose(tf.compat.v1.nn.embedding_lookup(self.g_embeddings, self.x),
                                            perm=[1, 0, 2])  # seq_length x batch_size x emb_dim

        ta_emb_x = tensor_array_ops.TensorArray(
            dtype=tf.compat.v1.float32, size=self.sequence_length)
        ta_emb_x = ta_emb_x.unstack(self.processed_x)

        ta_x = tensor_array_ops.TensorArray(dtype=tf.compat.v1.int32, size=self.sequence_length)
        ta_x = ta_x.unstack(tf.compat.v1.transpose(self.x, perm=[1, 0]))
        #####################################################################################################

        self.h0 = tf.compat.v1.zeros([self.batch_size, self.hidden_dim])
        self.h0 = tf.compat.v1.stack([self.h0, self.h0])

        gen_x = tensor_array_ops.TensorArray(dtype=tf.compat.v1.int32, size=self.sequence_length,
                                             dynamic_size=False, infer_shape=True)

        # When current index i < given_num, use the provided tokens as the input at each time step
        def _g_recurrence_1(i, x_t, h_tm1, given_num, gen_x):
            h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            x_tp1 = ta_emb_x.read(i)
            gen_x = gen_x.write(i, ta_x.read(i))
            return i + 1, x_tp1, h_t, given_num, gen_x

        # When current index i >= given_num, start roll-out, use the output as time step t as the input at time step t+1
        def _g_recurrence_2(i, x_t, h_tm1, given_num, gen_x):
            h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            o_t = self.g_output_unit(h_t)  # batch x vocab , logits not prob
            log_prob = tf.compat.v1.log(tf.compat.v1.nn.softmax(o_t))
            next_token = tf.compat.v1.cast(tf.compat.v1.reshape(tf.compat.v1.multinomial(log_prob, 1), [self.batch_size]), tf.compat.v1.int32)
            x_tp1 = tf.compat.v1.nn.embedding_lookup(self.g_embeddings, next_token)  # batch x emb_dim
            gen_x = gen_x.write(i, next_token)  # indices, batch_size
            return i + 1, x_tp1, h_t, given_num, gen_x

        i, x_t, h_tm1, given_num, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, given_num, _4: i < given_num,
            body=_g_recurrence_1,
            loop_vars=(tf.compat.v1.constant(0, dtype=tf.compat.v1.int32),
                       tf.compat.v1.nn.embedding_lookup(self.g_embeddings, self.start_token), self.h0, self.given_num, gen_x))

        _, _, _, _, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, _3, _4: i < self.sequence_length,
            body=_g_recurrence_2,
            loop_vars=(i, x_t, h_tm1, given_num, self.gen_x))

        self.gen_x = self.gen_x.stack()  # seq_length x batch_size
        self.gen_x = tf.compat.v1.transpose(self.gen_x, perm=[1, 0])  # batch_size x seq_length

    def get_reward(self, sess, input_x, rollout_num, discriminator):
        rewards = []
        for i in range(rollout_num):
            for given_num in range(1, len(input_x[0])):
                feed = {self.x: input_x, self.given_num: given_num}
                samples = sess.run(self.gen_x, feed)
                feed = {discriminator.input_x: samples}
                ypred_for_auc = sess.run(discriminator.ypred_for_auc, feed)
                ypred = np.array([item[1] for item in ypred_for_auc])
                if i == 0:
                    rewards.append(ypred)
                else:
                    rewards[given_num - 1] += ypred

            # the last token reward
            feed = {discriminator.input_x: input_x}
            ypred_for_auc = sess.run(discriminator.ypred_for_auc, feed)
            ypred = np.array([item[1] for item in ypred_for_auc])
            if i == 0:
                rewards.append(ypred)
            else:
                rewards[(len(input_x[0])-1)] += ypred

        reward_res = np.transpose(np.array(rewards)) / (1.0 * rollout_num)  # batch_size x seq_length
        return reward_res

    def create_recurrent_unit(self):
        # Weights and Bias for input and hidden tensor
        self.Wi = tf.compat.v1.identity(self.lstm.Wi)
        self.Ui = tf.compat.v1.identity(self.lstm.Ui)
        self.bi = tf.compat.v1.identity(self.lstm.bi)

        self.Wf = tf.compat.v1.identity(self.lstm.Wf)
        self.Uf = tf.compat.v1.identity(self.lstm.Uf)
        self.bf = tf.compat.v1.identity(self.lstm.bf)

        self.Wog = tf.compat.v1.identity(self.lstm.Wog)
        self.Uog = tf.compat.v1.identity(self.lstm.Uog)
        self.bog = tf.compat.v1.identity(self.lstm.bog)

        self.Wc = tf.compat.v1.identity(self.lstm.Wc)
        self.Uc = tf.compat.v1.identity(self.lstm.Uc)
        self.bc = tf.compat.v1.identity(self.lstm.bc)

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.compat.v1.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wi) +
                tf.compat.v1.matmul(previous_hidden_state, self.Ui) + self.bi
            )

            # Forget Gate
            f = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wf) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uf) + self.bf
            )

            # Output Gate
            o = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wog) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uog) + self.bog
            )

            # New Memory Cell
            c_ = tf.compat.v1.nn.tanh(
                tf.compat.v1.matmul(x, self.Wc) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uc) + self.bc
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.compat.v1.nn.tanh(c)

            return tf.compat.v1.stack([current_hidden_state, c])

        return unit

    def update_recurrent_unit(self):
        # Weights and Bias for input and hidden tensor
        self.Wi = self.update_rate * self.Wi + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Wi)
        self.Ui = self.update_rate * self.Ui + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Ui)
        self.bi = self.update_rate * self.bi + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.bi)

        self.Wf = self.update_rate * self.Wf + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Wf)
        self.Uf = self.update_rate * self.Uf + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Uf)
        self.bf = self.update_rate * self.bf + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.bf)

        self.Wog = self.update_rate * self.Wog + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Wog)
        self.Uog = self.update_rate * self.Uog + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Uog)
        self.bog = self.update_rate * self.bog + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.bog)

        self.Wc = self.update_rate * self.Wc + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Wc)
        self.Uc = self.update_rate * self.Uc + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Uc)
        self.bc = self.update_rate * self.bc + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.bc)

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.compat.v1.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wi) +
                tf.compat.v1.matmul(previous_hidden_state, self.Ui) + self.bi
            )

            # Forget Gate
            f = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wf) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uf) + self.bf
            )

            # Output Gate
            o = tf.compat.v1.sigmoid(
                tf.compat.v1.matmul(x, self.Wog) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uog) + self.bog
            )

            # New Memory Cell
            c_ = tf.compat.v1.nn.tanh(
                tf.compat.v1.matmul(x, self.Wc) +
                tf.compat.v1.matmul(previous_hidden_state, self.Uc) + self.bc
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.compat.v1.nn.tanh(c)

            return tf.compat.v1.stack([current_hidden_state, c])

        return unit

    def create_output_unit(self):
        self.Wo = tf.compat.v1.identity(self.lstm.Wo)
        self.bo = tf.compat.v1.identity(self.lstm.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.compat.v1.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.compat.v1.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.compat.v1.nn.softmax(logits)
            return logits

        return unit

    def update_output_unit(self):
        self.Wo = self.update_rate * self.Wo + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.Wo)
        self.bo = self.update_rate * self.bo + (1 - self.update_rate) * tf.compat.v1.identity(self.lstm.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.compat.v1.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.compat.v1.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.compat.v1.nn.softmax(logits)
            return logits
        return unit

    def update_params(self):
        self.g_embeddings = tf.compat.v1.identity(self.lstm.g_embeddings)
        self.g_recurrent_unit = self.update_recurrent_unit()
        self.g_output_unit = self.update_output_unit()
